inherit_from: .rubocop_todo.yml

Style/NumericPredicate:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'spec/code_object_spec.rb'
    - 'lib/pry/method.rb'
    - 'lib/pry/wrapped_module.rb'
    - 'lib/pry/code.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/pry/config/behavior.rb'

Layout/CommentIndentation:
  Exclude:
    - 'spec/fixtures/example_nesting.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/fixtures/example_nesting.rb'

# TODO: delete exclusions when we drop Ruby 1.9.3 support.
Style/ExpandPathArguments:
  Exclude:
    - 'lib/pry/commands.rb'
    - 'pry.gemspec'
