version: 2.1

jobs:
  build:
    working_directory: ~/pry

    docker:
      - image: kyrylo/ruby-1.9.3p551

    steps:
      - checkout

      - run:
          name: Install Bundler dependencies
          command: bundle install

      - run:
          name: Install Nano text editor (required for some tests)
          command: apk add nano

      - run:
          name: Run unit tests
          command: bundle exec rake
          environment:
            # Make sure TERM is set so Pry can indent correctly inside tests.
            TERM: screen-256color
